openapi: 3.0.3
info:
  title: Tarako
  version: '0.1'
  description: タスク管理アプリケーションバのックエンドAPI

paths:
  /users:
    get:
      tags:
        - user
      parameters:
        - name: department
          in: query
          description: 部署絞り込み。指定しなかった場合、すべての部署
          required: false
          schema:
            type: string
            example: 人事部
      responses:
        '200':
          $ref: '#/components/responses/UserArray'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersGetFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /users/{user_id}:
    get:
      tags:
        - user
      description: ユーザー詳細の取得
      parameters:
        - $ref: '#/components/parameters/user_id_path'
      responses:
        '200':
          $ref: '#/components/responses/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersGetUserFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    patch:
      description: ユーザー情報の更新。管理者を除き、自分の情報のみ更新可能
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/user_id_path'
      requestBody:
        $ref: '#/components/requestBodies/EditUser'
      responses:
        '200':
          $ref: '#/components/responses/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersPatchUserFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /tasks:
    get:
      tags:
        - task
      parameters:
        - $ref: '#/components/parameters/not_assigned'
        - $ref: '#/components/parameters/user_id_query' # NOTE: 複数ユーザーを受け付ける形にする
        - $ref: '#/components/parameters/from_datetime_query'
        - $ref: '#/components/parameters/to_datetime_query'
        - name: status
          in: query
          description: 進行中か否かで絞り込み。指定しなかった場合、現状での絞り込みを行わない
          required: false
          schema:
            type: string
            enum:
              - in_progress
              - completed
      responses:
        '200':
          $ref: '#/components/responses/TaskArray'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksGetFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    post:
      tags:
        - task
      description: タスクの投稿
      parameters:
        - name: force_create
          in: query
          description: すでに存在するタスクを強制的に作成するかどうか。指定しなかった場合、変更を提案されることがある。
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        $ref: '#/components/requestBodies/CreateTask'
      responses:
        '201':
          $ref: '#/components/responses/Task'
        '208':
          $ref: '#/components/responses/SuggestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksPostFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy

  /tasks/{task_id}:
    get:
      tags:
        - task
      description: タスク詳細の取得
      parameters:
        - $ref: '#/components/parameters/task_id_path'
      responses:
        '200':
          $ref: '#/components/responses/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksGetTaskFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    put:
      tags:
        - task
      description: タスクを更新する。
      parameters:
        - $ref: '#/components/parameters/task_id_path'
      requestBody:
        $ref: '#/components/requestBodies/UpdateTask'
      responses:
        '200':
          $ref: '#/components/responses/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksPutTaskFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    delete:
      tags:
        - task
      description: タスクの削除
      parameters:
        - $ref: '#/components/parameters/task_id_path'
      responses:
        '200':
          description: 正常削除
        '404':
          $ref: '#/components/responses/404NotFound'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksDeleteTaskFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy

  /diary/users:
    get:
      tags:
        - user_diary
      description: 全員の日報一覧
      parameters:
        - $ref: '#/components/parameters/from_date_query'
        - $ref: '#/components/parameters/to_date_query'
      responses:
        '200':
          $ref: '#/components/responses/UserDiaryArray'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersGetFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /diary/users/{user_id}:
    get:
      tags:
        - user_diary
      description: ユーザーの日報一覧
      parameters:
        - $ref: '#/components/parameters/user_id_path'
        - $ref: '#/components/parameters/from_date_query'
        - $ref: '#/components/parameters/to_date_query'
      responses:
        '200':
          $ref: '#/components/responses/UserDiaryArray'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersGetUserFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    post:
      tags:
        - user_diary
      description: 日報を作成
      parameters:
        - $ref: '#/components/parameters/user_id_path'
      requestBody:
        $ref: '#/components/requestBodies/PostUserDiary'
      responses:
        '201':
          $ref: '#/components/responses/UserDiary'
        '409':
          $ref: '#/components/responses/409Conflict'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersPostUserFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /diary/users/{user_id}/{diary_id}:
    get:
      tags:
        - user_diary
      description: 日報詳細
      parameters:
        - $ref: '#/components/parameters/user_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      responses:
        '200':
          $ref: '#/components/responses/UserDiary'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersGetUserDiaryFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    put:
      tags:
        - user_diary
      description: 日報の更新
      parameters:
        - $ref: '#/components/parameters/user_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      requestBody:
        $ref: '#/components/requestBodies/PutUserDiary'
      responses:
        '200':
          $ref: '#/components/responses/UserDiary'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersPutUserDiaryFunction.Arn}/invocations'
        httpMethod: PUT
        type: aws_proxy
    delete:
      tags:
        - user_diary
      description: 日報の削除
      parameters:
        - $ref: '#/components/parameters/user_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      responses:
        '200':
          description: 正常削除
        '404':
          $ref: '#/components/responses/404NotFound'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiaryUsersDeleteUserDiaryFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /diary/sections:
    get:
      tags:
        - section_diary
      description: 全課の日報一覧
      parameters:
        - $ref: '#/components/parameters/from_date_query'
        - $ref: '#/components/parameters/to_date_query'
      responses:
        '200':
          $ref: '#/components/responses/SectionDiaryArray'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsGetFunction.Arn}/invocations'
        httpMethod: GET
        type: aws_proxy
  /diary/sections/{section_id}:
    get:
      tags:
        - section_diary
      parameters:
        - $ref: '#/components/parameters/section_id_path'
        - $ref: '#/components/parameters/from_date_query'
        - $ref: '#/components/parameters/to_date_query'
      responses:
        '200':
          $ref: '#/components/responses/SectionDiaryArray'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsGetSectionFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
    post:
      tags:
        - section_diary
      description: 課に所属しているユーザーの日報から、課の日報を作成
      parameters:
        - $ref: '#/components/parameters/section_id_path'
      requestBody:
        $ref: '#/components/requestBodies/PostSectionDiary'
      responses:
        '201':
          $ref: '#/components/responses/SectionDiary'
        '409':
          $ref: '#/components/responses/409Conflict'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsPostSectionFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
  /diary/sections/{section_id}/{diary_id}:
    get:
      tags:
        - section_diary
      description: 日報詳細
      parameters:
        - $ref: '#/components/parameters/section_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      responses:
        '200':
          $ref: '#/components/responses/SectionDiary'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsGetSectionDiaryFunction.Arn}/invocations'
        httpMethod: GET
        type: aws_proxy
    put:
      tags:
        - section_diary
      description: 日報の更新
      parameters:
        - $ref: '#/components/parameters/section_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      requestBody:
        $ref: '#/components/requestBodies/PutSectionDiary'
      responses:
        '200':
          $ref: '#/components/responses/SectionDiary'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsPutSectionDiaryFunction.Arn}/invocations'
        httpMethod: PUT
        type: aws_proxy
    delete:
      tags:
        - section_diary
      description: 日報の削除
      parameters:
        - $ref: '#/components/parameters/section_id_path'
        - $ref: '#/components/parameters/diary_id_path'
      responses:
        '200':
          description: 正常削除
        '404':
          $ref: '#/components/responses/404NotFound'
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DiarySectionsDeleteSectionDiaryFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    RequestText:
      type: string
      description: タスクの詳細
      example: hoge.fugaの単体テストを作成した
    RequestFile:
      type: string
      format: binary
      description: タスクで作成したファイル
      example: hoge.docx
    RequestTaskAndFile:
      type: object
      properties:
        text:
          $ref: '#/components/schemas/RequestText'
        file:
          $ref: '#/components/schemas/RequestFile'

    createdAt:
      # type: string
      format: datetime
      description: 作成日時
      readOnly: true
      example: 2020-01-01T00:00:00+09:00
    updatedAt:
      type: string
      format: datetime
      description: 更新日時
      readOnly: true
      example: 2020-01-01T00:00:00+09:00

    ProgressItem:
      description: 進捗状況
      type: object
      properties:
        datetime:
          type: string
          format: datetime
        percentage:
          type: integer
          format: int32
          description: 進捗率
          minimum: 0
          maximum: 100

    SectionId:
      type: integer
      format: int32
      description: 課ID
      readOnly: true
    Section:
      type: object
      properties:
        section_id:
          $ref: '#/components/schemas/SectionId'
        name:
          type: string
          description: 課名
          example: 人事課
        created_at:
          $ref: '#/components/schemas/createdAt'
        updated_at:
          $ref: '#/components/schemas/updatedAt'

    UserId:
      type: string
      format: uuid
      description: ユーザーID
      readOnly: false

    User:
      type: object
      properties:
        user_id:
          $ref: '#/components/schemas/UserId'
        name:
          type: string
          example: 細井颯太
        email:
          type: string
          format: email
        department:
          type: string
          description: 部署名
          example: 人事部
        section:
          $ref: '#/components/schemas/Section'
        created_at:
          $ref: '#/components/schemas/createdAt'
        updated_at:
          $ref: '#/components/schemas/updatedAt'

    TaskId:
      type: string
      description: タスクID
      format: uuid
      readOnly: true

    TaskCategory: # タスクのカテゴリー。固定のものを用意する
      type: string
      description: タスクのカテゴリー
      enum:
        - 人事
        - 経理
        - 総務
        - 日報
        - その他

    Task:
      type: object
      properties:
        task_id:
          $ref: '#/components/schemas/TaskId'
        assigned_by:
          description: タスクの担当者。タスク自体はあるが、担当者がまだいない場合がある
          allOf:
            - $ref: '#/components/schemas/UserId'
          nullable: true
        title:
          type: string
          description: タスク名
          example: 単体テスト作成
        category:
          $ref: '#/components/schemas/TaskCategory'
        progresses:
          type: array
          description: 進捗状況リスト
          items:
            $ref: '#/components/schemas/ProgressItem'
          example:
            - datetime: 2020-01-01T00:00:00+09:00
              percentage: 0
            - datetime: 2020-01-02T00:00:00+09:00
              percentage: 50
            - datetime: 2020-01-03T00:00:00+09:00
              percentage: 100
        completed:
          type: boolean
          description: タスクが完了したかどうか。progressesから自動的に判定される。検索の高速化のために存在
          example: true
          readOnly: true
        serious:
          type: integer
          description: 深刻度
          minimum: 0
          maximum: 5
          example: 0
        details:
          type: string
          description: タスクの詳細
          example: hoge.fugaの単体テストを作成する
        created_at:
          $ref: '#/components/schemas/createdAt'
        updated_at:
          $ref: '#/components/schemas/updatedAt'

    DiaryId:
      type: string
      format: uuid
      description: 日報ID
      readOnly: true
    DiaryBase:
      type: object
      properties:
        diary_id:
          $ref: '#/components/schemas/DiaryId'
        date:
          type: string
          format: date
          description: 日報の日付
          readOnly: true
        details:
          type: string
          description: タスクの詳細
          example: hoge.fugaの単体テストを作成する
        serious:
          type: integer
          description: 深刻度の総計
          minimum: 0
        task_ids:
          type: array
          description: 日報の作成に用いられたタスクのIDリスト
          items:
            $ref: '#/components/schemas/TaskId'
        created_at:
          $ref: '#/components/schemas/createdAt'
        updated_at:
          $ref: '#/components/schemas/updatedAt'
    UserDiary:
      type: object
      allOf:
        - $ref: '#/components/schemas/DiaryBase'
      properties:
        user_id:
          allOf:
            - $ref: '#/components/schemas/UserId'
          readOnly: true
    SectionDiary:
      type: object
      allOf:
        - $ref: '#/components/schemas/DiaryBase'
      properties:
        section:
          allOf:
            - $ref: '#/components/schemas/Section'
          readOnly: true
    CreateDiary:
      type: object
      properties:
        date:
          type: string
          format: date
          description: 日報の日付

  parameters:
    task_id_path:
      name: task_id
      in: path
      required: True
      schema:
        $ref: '#/components/schemas/TaskId'
    user_id_path:
      name: user_id
      in: path
      required: True
      schema:
        $ref: '#/components/schemas/UserId'
    diary_id_path:
      name: diary_id
      in: path
      required: True
      schema:
        $ref: '#/components/schemas/DiaryId'
    section_id_path:
      name: section_id
      in: path
      required: True
      schema:
        type: string
        format: uuid
        description: 課ID
    from_datetime_query:
      name: from
      in: query
      description: タスクの開始期間で絞り込み。指定しなかった場合、制限なし
      required: false
      schema:
        type: string
        format: datetime
        example: 2020-01-01T00:00:00+09:00
    to_datetime_query:
      name: to
      in: query
      description: タスクの終了期間で絞り込み。指定しなかった場合、制限なし
      required: false
      schema:
        type: string
        format: datetime
        example: 2020-01-01T00:00:00+09:00
    from_date_query:
      name: from
      in: query
      description: 開始日で絞り込み。指定しなかった場合、制限なし
      required: false
      schema:
        type: string
        format: date
        example: 2020-01-01
    to_date_query:
      name: to
      in: query
      description: 終了日で絞り込み。指定しなかった場合、制限なし
      required: false
      schema:
        type: string
        format: date
        example: 2020-01-01

    user_id_query:
      name: user_id
      in: query
      description: ユーザー絞り込み。note_assignedがtrueの場合、無視される
      required: False
      schema:
        $ref: '#/components/schemas/UserId'
    not_assigned:
      name: not_assigned
      in: query
      description: 担当者がいないタスクを絞り込む。user_id_queryよりも優先される
      required: False
      schema:
        type: boolean
        default: false

  responses:
    404NotFound:
      description: The specified resource was not found.
    409Conflict:
      description: The request could not be completed due to a conflict with the current state of the target resource.
    UnauthorizedError:
      description: Access token is missing or invalid
    User:
      description: ユーザーの詳細
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    UserArray:
      description: ユーザーの一覧
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    Task:
      description: タスクの詳細
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Task'
    TaskArray:
      description: タスクの一覧
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Task'
    SuggestResponse:
      description: タスクの更新を提案する
      content:
        application/json:
          schema:
            type: object
            properties:
              Task:
                $ref: '#/components/schemas/Task'
              message:
                type: string
                description: 提案の理由
                example: 似たタスクを発見しました。\nこちらのタスクを更新しますか？

    UserDiary:
      description: ユーザーの日報の詳細
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserDiary'
    UserDiaryArray:
      description: ユーザーの日報一覧
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserDiary'
    SectionDiary:
      description: 課の日報の詳細
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SectionDiary'
    SectionDiaryArray:
      description: 課の日報一覧
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SectionDiary'

  requestBodies:
    CreateTask:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/RequestText'
              - $ref: '#/components/schemas/RequestFile'
              - $ref: '#/components/schemas/RequestTaskAndFile'
          examples:
            requestText:
              value:
                text: hoge.fugaの単体テストを作成した
            requestFile:
              value:
                file: hoge.docx
            requestTaskAndFile:
              value:
                text: hoge.fugaの単体テストを作成した
                file: fuga.docx
    UpdateTask:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/Task'
              - $ref: '#/components/schemas/RequestText'
              - $ref: '#/components/schemas/RequestFile'
              - $ref: '#/components/schemas/RequestTaskAndFile'
          examples:
            Task:
              value:
                title: 単体テスト作成
                category: 人事
                progresses:
                  - datetime: 2020-01-01T00:00:00+09:00
                    percentage: 0
                  - datetime: 2020-01-02T00:00:00+09:00
                    percentage: 50
                  - datetime: 2020-01-03T00:00:00+09:00
                    percentage: 100
                serious: 0
                details: hoge.fugaの単体テストを作成する
            requestText:
              value:
                text: hoge.fugaの単体テストを作成した
            requestFile:
              value:
                file: hoge.docx
            requestTaskAndFile:
              value:
                text: hoge.fugaの単体テストを作成した
                file: fuga.docx
    EditUser:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

    PostUserDiary:
      required: true
      description: 日報の作成
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateDiary'
    PostSectionDiary:
      required: true
      description: 日報の作成
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateDiary'
    PutUserDiary:
      required: true
      description: 日報の更新
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserDiary'
    PutSectionDiary:
      required: true
      description: 日報の更新
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SectionDiary'
